In [16]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [17]:
read_file = pd.read_csv (r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TrainingRatings.txt')
read_file.to_csv (r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TrainingRatings.csv', index=None)
cols = ['MovieID', 'UserID', 'Rating']
training = pd.read_csv(r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TrainingRatings.csv', names=cols)
training.head()

MovieID   UserID  Rating
0        8  1744889     1.0
1        8  1395430     2.0
2        8  1205593     4.0
3        8  1488844     4.0
4        8  1447354     1.0

In [18]:
with open(r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\movie_titles.txt') as fl:

    no = [ len(l.split(",")) for l in fl.readlines() ]


column_names = [i for i in range(0, max(no))]


df1 = pd.read_csv(r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\movie_titles.txt', header=None, delimiter=",", names=column_names, encoding='latin1')

df1.to_csv('movie_titles.csv')

In [19]:
df2 = pd.read_csv(r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\movie_titles.csv')
movies = df2.iloc[:, 1:4]
movies.head()

0       1                             2
0  1  2003.0               Dinosaur Planet
1  2  2004.0    Isle of Man TT 2004 Review
2  3  1997.0                     Character
3  4  1994.0  Paula Abdul's Get Up & Dance
4  5  2004.0      The Rise and Fall of ECW

In [20]:
import pandas as pd

read_file = pd.read_csv (r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TestingRatings.txt')
read_file.to_csv (r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TestingRatings.csv', index=None)
cols = ['MovieID', 'UserID', 'Rating']
testing = pd.read_csv(r'C:\Users\Yash\Documents\0_ML\0_HW\hw2\netflix\TestingRatings.csv', names=cols)
testing.head()

MovieID   UserID  Rating
0        8   573364     1.0
1        8  2149668     3.0
2        8  1089184     3.0
3        8  2465894     3.0
4        8   534508     1.0

In [21]:
print(training.shape)
print(testing.shape)
print(movies.shape)

(3255352, 3)
(100478, 3)
(17770, 3)


In [22]:
print("Unique UserID:",training.UserID.unique().shape[0])
n_users = training.UserID.unique()
print(n_users.shape)
print("Unique MovieID:",training.MovieID.unique().shape[0])
n_mov = training.MovieID.unique()
print(n_mov.shape)

Unique UserID: 28978
(28978,)
Unique MovieID: 1821
(1821,)


In [23]:
training1 = training.groupby('UserID', as_index = False, sort = False).mean().rename(columns={"UserID": "UserID",
                                                                                         "Rating": "mean_rating",
                                                                                           "MovieID": "MovieID"})
training1['Centered_ratings'] = training1['mean_rating'] - training['Rating']
training1.head()

UserID      MovieID  mean_rating  Centered_ratings
0  1744889  8442.270588     2.450980          1.450980
1  1395430  8369.293333     3.160000          1.160000
2  1205593  8451.303030     3.535354         -0.464646
3  1488844  8887.320175     3.184211         -0.815789
4  1447354  8190.746835     3.291139          2.291139

In [24]:
df_t = training.pivot_table(
    index='UserID',
    columns='MovieID',
    values='Rating'
).fillna(0)
df_t

MovieID  8      28     43     48     61     64     66     92     96     111    \
UserID                                                                          
7          5.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
79         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
199        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
481        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    5.0   
769        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2648869    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2648885    0.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649120    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649267    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    3.0   
2649285    0.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

MovieID  ...  17654  17660  17689  17693  17706  17725  17728  17734  17741  \
UserID   ...                                                                  
7        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
79       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
199      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
481      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
769      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2648869  ...    0.0    0.0    0.0    0.0    0.0    5.0    0.0    0.0    0.0   
2648885  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649120  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649267  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649285  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

MovieID  17742  
UserID          
7          0.0  
79         0.0  
199        0.0  
481        0.0  
769        0.0  
...        ...  
2648869    0.0  
2648885    0.0  
2649120    0.0  
2649267    0.0  
2649285    0.0  

[28978 rows x 1821 columns]

In [25]:
testing1 = testing.groupby('UserID', as_index = False, sort = False).mean().rename(columns={"UserID": "UserID",
                                                                                         "Rating": "mean_rating",
                                                                                           "MovieID": "MovieID"})
testing1['Centered_ratings'] = testing1['mean_rating'] - testing['Rating']
testing1.head()

UserID       MovieID  mean_rating  Centered_ratings
0   573364   1489.750000     2.750000          1.750000
1  2149668   6126.666667     3.333333          0.333333
2  1089184   5042.500000     1.750000         -1.250000
3  2465894   9456.750000     3.125000          0.125000
4   534508  12547.333333     2.333333          1.333333

In [26]:
df_t1 = testing.pivot_table(
    index='UserID',
    columns='MovieID',
    values='Rating'
).fillna(0)
df_t1

MovieID  8      28     43     48     61     64     66     92     96     111    \
UserID                                                                          
7          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
79         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
199        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
481        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
769        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2648869    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2648885    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649120    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649267    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649285    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

MovieID  ...  17653  17654  17689  17693  17706  17725  17728  17734  17741  \
UserID   ...                                                                  
7        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
79       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
199      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
481      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
769      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2648869  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2648885  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649120  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649267  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649285  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

MovieID  17742  
UserID          
7          0.0  
79         0.0  
199        0.0  
481        0.0  
769        0.0  
...        ...  
2648869    0.0  
2648885    0.0  
2649120    0.0  
2649267    0.0  
2649285    0.0  

[27555 rows x 1701 columns]

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

cos_sim = cosine_similarity(df_t)
cos_df = pd.DataFrame(cos_sim)
cos_df.head()

0         1         2         3         4         5         6      \
0  1.000000  0.419577  0.390199  0.396505  0.329977  0.354751  0.405943   
1  0.419577  1.000000  0.361859  0.347347  0.274105  0.252087  0.378628   
2  0.390199  0.361859  1.000000  0.359243  0.446866  0.335329  0.260398   
3  0.396505  0.347347  0.359243  1.000000  0.235097  0.186047  0.299789   
4  0.329977  0.274105  0.446866  0.235097  1.000000  0.464661  0.319184   

      7         8         9      ...     28968     28969     28970     28971  \
0  0.323210  0.377308  0.403701  ...  0.392724  0.436621  0.443371  0.333261   
1  0.265942  0.279955  0.422563  ...  0.326537  0.414813  0.452799  0.368334   
2  0.259962  0.347957  0.368324  ...  0.533831  0.422769  0.479515  0.393458   
3  0.236803  0.253862  0.390080  ...  0.400851  0.341319  0.388550  0.353181   
4  0.309208  0.398546  0.326350  ...  0.400129  0.383400  0.415439  0.338099   

      28972     28973     28974     28975     28976     28977  
0  0.293030  0.334704  0.403255  0.371953  0.377588  0.469802  
1  0.339498  0.322260  0.320251  0.226118  0.351195  0.419483  
2  0.225604  0.398873  0.438069  0.391784  0.303931  0.291619  
3  0.253913  0.237703  0.404862  0.212481  0.364765  0.443812  
4  0.213743  0.450085  0.426718  0.550897  0.283284  0.242553  

[5 rows x 28978 columns]

In [28]:
train_data_matrix = df_t.to_numpy()
train_data_matrix[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [29]:
test_data_matrix = df_t1.to_numpy()
test_data_matrix.shape

(27555, 1701)

In [30]:
# assign weights
from numpy import sqrt 
def ass_w (user, other, data):
    sum = 0
    sum_u = 0
    sum_ou = 0
    n = 0
    rating1 = data[user]
    rating2 = data[other]
    leng = len(rating1)
    
    m1 = training1['mean_rating'][user]
    m2 = training1['mean_rating'][other]
    
    for i in range(leng):
        if rating1[i]>0: 
            if rating2[i]>0:
                n += 1
                sum += (rating1[i]-m1)*(rating2[i]-m2)
    
    if n == 0:
        return 0
    else:

        for value in rating1[:]:
            sum_u += value**2
        for value in rating2[:]:
            sum_ou += value**2

            
        f1 = sum_u - m1
        f2 = sum_ou - m2
        denominator = sqrt(sum_u) * sqrt(sum_ou)

        if denominator == 0:
            return 0
        else:
            return sum/denominator

ass_w(1,2,train_data_matrix)

1.444054271849517

In [32]:
# create weight matrix
n = len(train_data_matrix)
w = np.empty(shape=(n,n),dtype='object')
for i in range(n):
    for j in range(n):
        w[i][j] = 0

for i in range(n):
    for j in range(n):
        w[i][j] = ass_w(i,j,train_data_matrix)

In [17]:
# weights using pearson correlation
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = 1 - pairwise_distances(train_data_matrix, metric='correlation')

In [18]:
user_similarity

array([[1.        , 0.39042738, 0.36167557, ..., 0.34135417, 0.34682086,
        0.44040819],
       [0.39042738, 1.        , 0.33515094, ..., 0.19249217, 0.3226184 ,
        0.39103658],
       [0.36167557, 0.33515094, 1.        , ..., 0.36703766, 0.2752275 ,
        0.2591702 ],
       ...,
       [0.34135417, 0.19249217, 0.36703766, ..., 1.        , 0.18851034,
        0.19507568],
       [0.34682086, 0.3226184 , 0.2752275 , ..., 0.18851034, 1.        ,
        0.38350054],
       [0.44040819, 0.39103658, 0.2591702 , ..., 0.19507568, 0.38350054,
        1.        ]])

In [60]:
def predictions(data, user_sim):
    user_mean = data.mean(axis=1)
    difference = (data - user_mean[:, np.newaxis])
    pred = user_mean[:, np.newaxis] + user_sim.dot(difference) / np.array([np.abs(user_sim).sum(axis=1)]).T
    return pred

In [61]:
user_prediction = predictions(train_data_matrix, user_similarity)

In [62]:
user_prediction

array([[ 0.30285949,  1.66704927,  0.01018654, ...,  0.00988412,
         0.10450984,  0.02835805],
       [ 0.22034312,  1.66914229, -0.04432658, ..., -0.04500696,
         0.0455549 , -0.02587305],
       [ 0.23127848,  1.47083876, -0.05768896, ..., -0.05836756,
         0.04461506, -0.04305203],
       ...,
       [ 0.26703228,  1.39748047, -0.04762261, ..., -0.0474745 ,
         0.0564629 , -0.03193035],
       [ 0.23848444,  1.66317925, -0.03932888, ..., -0.03966633,
         0.0547782 , -0.02096348],
       [ 0.22861537,  1.74090927, -0.04278736, ..., -0.04374487,
         0.05511568, -0.02424905]])

In [63]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def err(pred_value, true_val):
    pred_value = pred_value[true_val.nonzero()].flatten()
    true_val = true_val[true_val.nonzero()].flatten()
    return sqrt(mean_squared_error(pred_value, true_val))

In [64]:
print('User-based CF RMSE:', err(user_prediction, test_data_matrix))

User-based CF RMSE: 3.4660140544492255
