In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.svm import SVC
from sklearn.metrics import classification_report, zero_one_loss, confusion_matrix, accuracy_score

In [4]:
# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
X = X / 255.
X.shape

(70000, 784)

In [5]:
# rescale the data, use the traditional train/test split

X_train, X_test = X[:60000], X[60000:]
y_train, y_test = y[:60000], y[60000:]

In [6]:
# Using linear kernel and gamma scale and rest is set to default
svc_linear = SVC(kernel='linear', random_state=None, gamma='scale')
svc_linear.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
y_pred = svc_linear.predict(X_test)

In [8]:
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
error = zero_one_loss(y_test, y_pred)
print(error)

              precision    recall  f1-score   support

           0       0.95      0.98      0.96       980
           1       0.97      0.99      0.98      1135
           2       0.93      0.94      0.93      1032
           3       0.91      0.94      0.92      1010
           4       0.94      0.96      0.95       982
           5       0.91      0.90      0.91       892
           6       0.96      0.95      0.95       958
           7       0.95      0.93      0.94      1028
           8       0.94      0.90      0.92       974
           9       0.95      0.91      0.93      1009

    accuracy                           0.94     10000
   macro avg       0.94      0.94      0.94     10000
weighted avg       0.94      0.94      0.94     10000

0.9404
0.059599999999999986


In [9]:
# Using linear kernel 
# regulization param is set to 100, gamma is set to auto and max iteration is set to 1000
svm_linear2 = SVC(C=100, kernel='linear', gamma='auto', max_iter=1000,
                  probability=False, random_state=None)
svm_linear2.fit(X_train, y_train)

C:\Users\Yash\anaconda3\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [10]:
y_pred1 = svm_linear2.predict(X_test)

In [11]:
print(classification_report(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
error1 = zero_one_loss(y_test, y_pred1)
print(error1)

              precision    recall  f1-score   support

           0       0.91      0.97      0.94       980
           1       0.89      0.95      0.92      1135
           2       0.80      0.82      0.81      1032
           3       0.73      0.78      0.75      1010
           4       0.78      0.82      0.80       982
           5       0.79      0.74      0.76       892
           6       0.93      0.91      0.92       958
           7       0.84      0.72      0.78      1028
           8       0.70      0.60      0.65       974
           9       0.63      0.68      0.66      1009

    accuracy                           0.80     10000
   macro avg       0.80      0.80      0.80     10000
weighted avg       0.80      0.80      0.80     10000

0.8014
0.8014


In [12]:
# Using poly kernel 
# regulization param is set to 1, gamma is set to scale and degree is set to 8
svc_poly = SVC(kernel='poly', degree=8, gamma='scale', random_state=None)
svc_poly.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
y_pred2 = svc_poly.predict(X_test)

In [14]:
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test,y_pred2))
error2 = zero_one_loss(y_test, y_pred2)
print(error2)

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       980
           1       0.56      0.99      0.71      1135
           2       0.97      0.86      0.92      1032
           3       0.96      0.87      0.91      1010
           4       0.98      0.86      0.92       982
           5       0.98      0.80      0.88       892
           6       0.98      0.89      0.93       958
           7       0.98      0.85      0.91      1028
           8       0.95      0.89      0.92       974
           9       0.97      0.88      0.92      1009

    accuracy                           0.89     10000
   macro avg       0.93      0.88      0.90     10000
weighted avg       0.92      0.89      0.90     10000

0.8865
0.8865


In [15]:
# Using poly kernel 
# regulization param is set to 100, gamma is set to auto, degree is set to 10 and max iterations are 1000
svc_poly1 = SVC(C=100, kernel='poly', degree=10, gamma='auto', max_iter=1000,
                  probability=False, random_state=None)
svc_poly1.fit(X_train, y_train)

C:\Users\Yash\anaconda3\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=10, gamma='auto', kernel='poly',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
y_pred3 = svc_poly1.predict(X_test)

In [17]:
print(classification_report(y_test, y_pred3))
print(accuracy_score(y_test,y_pred3))
error3 = zero_one_loss(y_test, y_pred3)
print(error3)

              precision    recall  f1-score   support

           0       0.94      0.13      0.23       980
           1       0.00      0.00      0.00      1135
           2       1.00      0.00      0.00      1032
           3       1.00      0.01      0.01      1010
           4       0.67      0.00      0.00       982
           5       0.00      0.00      0.00       892
           6       0.93      0.16      0.28       958
           7       0.50      0.00      0.00      1028
           8       0.21      0.09      0.13       974
           9       0.11      0.99      0.20      1009

    accuracy                           0.14     10000
   macro avg       0.54      0.14      0.09     10000
weighted avg       0.53      0.14      0.08     10000

0.139
0.139


C:\Users\Yash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
# Using rbf kernel 
# regulization param is set to 1, gamma is set to scale and random_state is None
svc_rbf = SVC(kernel='rbf', gamma='scale', random_state=None)
svc_rbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
y_pred4 = svc_rbf.predict(X_test)

In [20]:
print(classification_report(y_test, y_pred4))
print(accuracy_score(y_test,y_pred4))
error4 = zero_one_loss(y_test, y_pred4)
print(error4)

[[ 973    0    1    0    0    2    1    1    2    0]
 [   0 1126    3    1    0    1    1    1    2    0]
 [   6    1 1006    2    1    0    2    7    6    1]
 [   0    0    2  995    0    2    0    5    5    1]
 [   0    0    5    0  961    0    3    0    2   11]
 [   2    0    0    9    0  871    4    1    4    1]
 [   6    2    0    0    2    3  944    0    1    0]
 [   0    6   11    1    1    0    0  996    2   11]
 [   3    0    2    6    3    2    2    3  950    3]
 [   3    4    1    7   10    2    1    7    4  970]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      0.97   

In [21]:
# Using rbf kernel 
# regulization param is set to 100, gamma is set to auto, random_state is None and max iterations are 1000
svc_rbf1 = SVC(C=100, kernel='rbf', gamma='auto', max_iter=1000,
                  probability=False, random_state=None)
svc_rbf1.fit(X_train, y_train)

C:\Users\Yash\anaconda3\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
y_pred5 = svc_rbf1.predict(X_test)

In [23]:
print(classification_report(y_test, y_pred5))
print(accuracy_score(y_test,y_pred5))
error5 = zero_one_loss(y_test, y_pred5)
print(error5)

[[ 971    0    2    2    0    3    1    0    1    0]
 [   0 1129    3    0    0    1    0    1    1    0]
 [   7    2 1004    1    1    0    2    6    8    1]
 [   0    0    3  982    0   10    0    4    7    4]
 [   0    0    7    0  956    1    2    0    0   16]
 [   5    1    1   11    2  861    4    1    3    3]
 [   6    2    3    0    2    6  936    0    3    0]
 [   1    3   13    3    3    0    0  990    1   14]
 [   5    2    4    8    2    4    3    5  939    2]
 [   2    5    0    6   14    3    0    9    3  967]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.97      0.97      0.97      1010
           4       0.98      0.97      0.97       982
           5       0.97      0.97      0.97       892
           6       0.99      0.98      0.98       958
           7       0.97      0.96   

In [24]:
# Using sigmoid kernel 
# regulization param is set to 1, gamma is set to scale and random_state is None
svc_sig = SVC(kernel='sigmoid', gamma='scale', random_state=None)
svc_sig.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [25]:
y_pred6 = svc_sig.predict(X_test)

In [26]:
print(classification_report(y_test, y_pred6))
print(accuracy_score(y_test,y_pred6))
error6 = zero_one_loss(y_test, y_pred6)
print(error6)

[[ 812    0   29    6    0   92   35    2    4    0]
 [   0 1073   13   15    0    3    4    1   26    0]
 [  29   44  779   25   20   15   46    6   60    8]
 [  29   10   38  725    2  120    6   14   42   24]
 [   5    5   11    1  830   11   19    4   18   78]
 [  48   24   12  107   14  591   20    6   59   11]
 [  17    5   75    2   31   35  784    0    9    0]
 [  25   15   38   11   17    6    0  850   13   53]
 [  24   40   31   32   30  128   11    9  624   45]
 [  18    6   16    8  121   31    0   73   45  691]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       980
           1       0.88      0.95      0.91      1135
           2       0.75      0.75      0.75      1032
           3       0.78      0.72      0.75      1010
           4       0.78      0.85      0.81       982
           5       0.57      0.66      0.61       892
           6       0.85      0.82      0.83       958
           7       0.88      0.83   

In [27]:
# Using sigmoid kernel 
# regulization param is set to 100, gamma is set to auto and max iterations are 1000
svc_sig2 = SVC(C=100, kernel='sigmoid', gamma='auto', max_iter=1000,
                  probability=False, random_state=None)
svc_sig2.fit(X_train, y_train)

C:\Users\Yash\anaconda3\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [28]:
y_pred7 = svc_sig2.predict(X_test)

In [29]:
print(classification_report(y_test, y_pred7))
print(accuracy_score(y_test,y_pred7))
error7 = zero_one_loss(y_test, y_pred7)
print(error7)

[[ 966    0    3    1    1    6    1    1    0    1]
 [   0 1123    2    2    0    1    2    1    4    0]
 [  10    3  949   15    7    3    8    7   30    0]
 [   3    0   22  924    0   27    0   10   22    2]
 [   1    1    6    1  941    0    6    2    2   22]
 [   9    4    3   55    5  771   12    1   30    2]
 [   6    3    9    1    5   16  917    1    0    0]
 [   1    7   24    8   10    0    0  922    1   55]
 [   7    8   10   40    9   38    6    5  847    4]
 [   4    8    2    9   41    4    0   32   10  899]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       980
           1       0.97      0.99      0.98      1135
           2       0.92      0.92      0.92      1032
           3       0.88      0.91      0.89      1010
           4       0.92      0.96      0.94       982
           5       0.89      0.86      0.88       892
           6       0.96      0.96      0.96       958
           7       0.94      0.90   

In [33]:
# Using rbf kernel 
# regulization param is set to 500, gamma is set to 0.05 and random_state is None
svc_cg = SVC(C=500, gamma=0.05, random_state=None)
svc_cg.fit(X_train, y_train)

SVC(C=500, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.05, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
y_pred8 = svc_cg.predict(X_test)

In [35]:
print(classification_report(y_test, y_pred8))
print(accuracy_score(y_test,y_pred8))
error8 = zero_one_loss(y_test, y_pred8)
print(error8)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.98      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      0.98      0.98      1028
           8       0.97      0.99      0.98       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

0.9837
0.01629999999999998


In [37]:
# Using rbf kernel 
# regulization param is set to 300, gamma is set to 0.005 and max iterations are 1000
svc_cg2 = SVC(C=300, gamma=0.005, max_iter=1000,
                  probability=False, random_state=None)
svc_cg2.fit(X_train, y_train)

C:\Users\Yash\anaconda3\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=300, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.005, kernel='rbf',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [38]:
y_pred9 = svc_cg2.predict(X_test)

In [39]:
print(classification_report(y_test, y_pred9))
print(accuracy_score(y_test,y_pred9))
error9 = zero_one_loss(y_test, y_pred9)
print(error9)

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.98      0.98      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.98      0.98       892
           6       0.99      0.98      0.99       958
           7       0.98      0.97      0.98      1028
           8       0.98      0.97      0.98       974
           9       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

0.9805
0.019499999999999962
